### ISSUE TITLE
General - Small Issues

### ISSUE THREAD

**Issue by gtarnowski** [EngineXMarketing/dmallied#2]
Here I'll list small issues, what needs to be fixed:

- [x] Add box shadow for each Team member tile on hover (like on listing tile, on the category page)
- [x] Each listing name on Basket dropdown should be bolded

**Comment by kamawietrzyk** [comment]
![Zrzut ekranu 2020-06-26 o 14 27 15](https://user-images.githubusercontent.com/44195056/85857079-7223c100-b7b9-11ea-9af3-7fe5f09f176b.png)
![Zrzut ekranu 2020-06-26 o 14 29 14](https://user-images.githubusercontent.com/44195056/85857089-751eb180-b7b9-11ea-8357-27e039df6a80.png)

**Comment by mattwietrzyk** [comment]
fixed
