### ISSUE TITLE
Listing Tile - Missing VIM

### ISSUE THREAD

**Issue by gtarnowski** [EngineXMarketing/dmallied#3]
Prevent from rendering an empty space and slash before price if there is no VIM number on listing tile![Screenshot 2020-06-22 at 11.40.15.png](https://images.zenhubusercontent.com/59fcc6618a75884b9085facd/b308bfce-1bab-4a9d-a840-db73cd9191a7)

**Comment by kamawietrzyk** [comment]
![Zrzut ekranu 2020-06-26 o 12 38 04](https://user-images.githubusercontent.com/44195056/85856739-cf6b4280-b7b8-11ea-98dd-64b555cff5c0.png)

**Comment by mattwietrzyk** [comment]
fixed
