### ISSUE TITLE
Listing Tile - name fixes

### ISSUE THREAD

**Issue by gtarnowski** [EngineXMarketing/dmallied#4]
There is a lot of space for the name on the listing, but some CSS rule is wrong to set. 

- [x] change behaviour of rendering listing name 
- [x] add a tooltip with full listing name
       * HINT: use `title` attribute on HTML element and put a full name there 
![Screenshot 2020-06-22 at 11.42.51.png](https://images.zenhubusercontent.com/59fcc6618a75884b9085facd/d5047f48-6887-46b0-880d-2aef00574c4e)

**Comment by kamawietrzyk** [comment]
![Zrzut ekranu 2020-06-26 o 15 13 01](https://user-images.githubusercontent.com/44195056/85860943-d34e9300-b7bf-11ea-8b5f-1cda0664579b.png)
![Zrzut ekranu 2020-06-26 o 15 14 49](https://user-images.githubusercontent.com/44195056/85860952-d6e21a00-b7bf-11ea-90ac-90209f917c7f.png)

**Comment by mattwietrzyk** [comment]
fixed
