### ISSUE TITLE
basket not refreshing

### ISSUE THREAD

**Issue by jaaaco** [EngineXMarketing/dmallied#7]
1. go to https://dev.dmallied.com/
2. click on a cart icon (basket)
3. go to some category and add an item to a basket
4. go back to basket: new item isn't there

**Comment by gtarnowski** [comment]
@jaaaco no longer occurs - closing

**Comment by gtarnowski** [comment]
@mattwietrzyk please look at the following case

**Comment by mattwietrzyk** [comment]
fixed
